baseURL = "https://amt8u-hugo-blog.netlify.app/"
languageCode = "en-us"
title = "cybercafe.dev"
theme="archie"
copyright = "© cybercafe.dev"
pygmentsstyle = "xcode-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	subtitle = "&#9829; I write about my learning and experiences here. This is a statically generated site from markdown content. [Read how I converted my blog](/creating-a-static-site-with-hugo) from ghostjs hosted app to static pages."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/amt8u"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/amt8u/"

[[params.social]]
name = "playground"
icon = "external-link"
url = "https://cybr.cafe"

[[menu.main]]
name = "javascript"
url = "/tags/javascript/"
weight = 1

[[menu.main]]
name = "gaming"
url = "/tags/gaming/"
weight = 2

[[menu.main]]
name = "web"
url = "/tags/web/"
weight = 3

[[menu.main]]
name = "all topics"
url = "/tags/"
weight = 5

[[menu.main]]
name = "all posts"
url = "/posts/"
weight = 8

[[menu.main]]
identifier = "amt8u"
name = "about"
url = "/amt8u/"
weight = 10


