languageCode = "en-AU"
languageName = "English (Australia)"
languageDirection = "ltr"
weight = 1

title = "cybercafe.dev"
copyright = "&copy; 2024 https://cybercafe.dev"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "amt8u"
  image = "amt8u_logo.png"
  headline = "Developer. Artist. Human."
  bio = "Developer. Artist. Human."
  links = [
    { x-twitter = "https://twitter.com/amt8u" },
    { facebook = "https://facebook.com/amt8u" },
    { linkedin = "https://linkedin.com/amt8u" },
    { youtube = "https://youtube.com/amt8u" },
  ]